Repository pluginsGLPI/news, pull requests merged in 2020-01, with the labels that each got.

#74 Update readme
  README.md
  glpi_network.png
  news.gif
  plugin.xml
  screenshot.png
Labels: enhancement

#73 fix(alert): add scrollbar if needed
  css/styles.css
Labels: bug, enhancement

#75 Fix notice on plugin install
  hook.php
Labels: bug
